version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: Asia/Ho_Chi_Minh
    open-pull-requests-limit: 5
    groups:
      development-dependencies:
        dependency-type: development
        update-types: [minor, patch]
      production-patch:
        dependency-type: production
        update-types: [patch]
    labels: ['dependencies']
    commit-message:
      prefix: 'chore(deps)'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels: ['dependencies', 'github-actions']
    commit-message:
      prefix: 'chore(ci)'
