// packages/core-chat/wordlist-en.ts — Danh sách từ tiếng Anh không văn minh.
// Phân loại theo mức độ: high (block), medium (filter), low (filter nhẹ).

export const EN_WORDS: Record<'high' | 'medium' | 'low', string[]> = {
  high: [
    'fuck',
    'fucking',
    'motherfucker',
    'motherfucking',
    'nigger',
    'nigga',
    'cunt',
    'faggot',
    'fag',
    'kike',
    'spic',
    'chink',
    'gook',
    'rape',
    'rapist',
    'kill yourself',
    'kys',
    'go die',
    'die bitch',
    'fucking die',
  ],
  medium: [
    'shit',
    'shitty',
    'bullshit',
    'asshole',
    'bastard',
    'bitch',
    'bitches',
    'son of a bitch',
    'dick',
    'pussy',
    'cock',
    'whore',
    'slut',
    'moron',
    'idiot',
    'dumbass',
    'dumb ass',
    'shut up',
    'stupid',
    'retard',
    'retarded',
  ],
  low: [
    'damn',
    'crap',
    'ass',
    'sucks',
    'jerk',
    'dork',
    'loser',
    'nerd',
    'freak',
    'ugly',
    'hate',
    'dumb',
  ],
}

// Leetspeak / obfuscation mappings để chuẩn hóa trước khi kiểm tra
export const LEET_MAP: Record<string, string> = {
  '@': 'a',
  '3': 'e',
  '1': 'i',
  '0': 'o',
  '5': 's',
  '7': 't',
  $: 's',
  '+': 't',
  '!': 'i',
  '|': 'l',
}
